spring:
  application:
    name: unittests
  datasource:
    url: jdbc:postgresql://localhost:5432/unittests
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
