services:
  db-unit-tests:
    image: postgres:17.5-alpine3.21
    container_name: db-unit-tests
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=unittests
    volumes:
      - db-unit-tests-data:/var/lib/postgresql/data
volumes:
  db-unit-tests-data:
